### PR TITLE
Add json definitions file

### PR DESCRIPTION
**Pull request by vincerubinetti**
Refs https://github.com/greenelab/hetmech-frontend/issues/16

Add `.json` file to contain definitions for metanodes, metaedges, and fields/properties. Primarily to be used for tooltip text.

### CODE REVIEW

**Comment by dhimmel** [comment]
One question is how we should encode metaedges. One option is abbreviations. Another is the metaedge tuple ids at:

https://github.com/hetio/hetionet/blob/b7c144da0dd428def9e3c262d0bc48c050cf631d/hetnet/json/hetionet-v1.0-metagraph.json#L15-L160

Lookup is potentially more complex than the metanode case because both orientations must be checked.

**Comment by vincerubinetti** [comment]
So does that mean there are definitions of the metaedges that are dependent on the metanodes that the edge is connecting? Is there no generic way to define "participates" or "upregulates" for example without knowing whether it's a gene, disease, etc.

I thought it would just be:
```json
...
"upregulates": "the process of increasing the response to a stimulus specifically",
...
```

Using the tuple ids seems better if necessary.

**Comment by dhimmel** [comment]
> So does that mean there are definitions of the metaedges that are dependent on the metanodes that the edge is connecting?

Yes. In reality, the identify of the metaedge depends on the metanodes it connects. Therefore the definitions should be different. See [`metaedge-styles.tsv`](https://github.com/hetio/hetionet/blob/b7c144da0dd428def9e3c262d0bc48c050cf631d/describe/edges/metaedge-styles.tsv) for possible styling. We also have disambiguated [relationship types](https://github.com/hetio/hetionet/blob/b7c144da0dd428def9e3c262d0bc48c050cf631d/hetnet/neo4j/types.tsv) we use for Neo4j.

**Comment by dhimmel** [comment]
We'll have to read over https://github.com/hetio/hetionet/pull/16/commits/eacfd9b0f46881be9745d3e5f9d42ee0cad377a8 to spot any errors.

**Comment by vincerubinetti** [comment]
Maybe let's try to make the sentences for metanodes consistent with the "from"? Like:

`Protein-coding human genes. From Entrez Gene.`

or 

`Complex diseases, selected to be distinct and specific enough to be clinically relevant yet general enough to be well annotated. From Disease Ontology.`

or 

`Anatomical structures, excluding structures that are known not to be found in humans. From Uberon`

And maybe we put `"` quotes around the sources to indicate that they're a source?

**Comment by dhimmel** [comment]
> And maybe we put " quotes around the sources to indicate that they're a source?

I think this would be a bit odd and perhaps unnecessary.

> Maybe let's try to make the sentences for metanodes consistent with the "from"? Like:

I've updated the metanode descriptions to conclude with from/From for consistency.

**Comment by vincerubinetti** [comment]
Looks good to me. Ready to merge.

**Pull request merged**
